spring:
  main:
    banner-mode: off
  zipkin:
    enabled: false
  sleuth:
    propagation:
      type: B3
  kafka:
    reservation:
      bootstrap-servers: localhost:29092
      consumer:
        group-id: omi-id
      topic:
        new-reservation: new-reservation
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: "pass"
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: always

trainDetailService:
  url: https://train-details-reservation-app-dev.trials.codenow.com

sleepConstant: 1000

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
