apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    buildNumber: "{{ .Values.buildNumber }}"
data:
  {{- range $key, $val := .Values.configFiles }}
  {{ $key -}}: |- {{ $val | b64dec | nindent 4 }}
  {{- end}}
  {{- (.Files.Glob "flyway/*.sql").AsConfig | nindent 2 }}